### PR TITLE
Implement ETH deposits and lock ups for tasks.

### PR DESCRIPTION
**Pull request by sinahab**
This PR does two high-level things:

- Enables users to deposit / withdraw ETH as deposit.
- Enables the Truebit contract to lock up / release user deposits as they engage with tasks as taskGiver, solver, or verifier.

The next step is to implement this for a TRU token.

Changes in this PR:

- Implement DepositManager contract for eth.
- Enable the taskBook contract to bond or unbond deposits as accounts create, solve, or verify tasks.
- Use SafeMath as a library.
- Write tests using async await, instead of chained promises.
- Change task_book.js to test for Events using the event name instead of a hard-coded index.
- Remove redundant test/exchange.js tests.
- Clean up package.json.
- Add doxygen comments.

### CODE REVIEW

**Comment by hswick** [comment]
Dope! Thanks for cleaning up the tests with async await.

The only thing I don't see that I was expecting was some kind of punish mechanism. I'm thinking some function that moves the bonded deposit into the jackpot.

**Comment by sinahab** [comment]
@hswick – good catch. Added it in the last commit. :)

**Comment by hswick** [comment]
Wait, just realized if there is a punish there should be a reward as well...

**Comment by sinahab** [comment]
@hswick – that one’s a bit more complicated. The rewarding function needs to transfer bonded deposits from one set of accounts to another. How it does that depends on how we implement the challenge games. I.e. if there’s multiple challengers at once and the solver is wrong, it will need to transfer the solver’s bonded deposit + the taskGiver’s reward to them. But if all the challenger’s are wrong and the solver is correct, the function needs to transfer their bonded deposits + the taskGiver’s reward to the solver. We also need to figure out how to divvy up bonded deposits between whoever wins the game and the jackpot.

Given the unknowns, maybe we should discuss this at the dev call, and implement in another PR?

**Comment by hswick** [comment]
@sinahab yeah much more complicated now that I think about it. Worth discussing with the rest of the team for sure.

**Comment by hswick** [comment]
Are you sure the tests passed after changing to keccac256? If they did, then I need to make the tests better.

**Comment by mrsmkl** [comment]
The tests pass, but sha3 is just the deprecated synonym for keccak256, not the version with standard padding

**Pull request merged**
