### PR TITLE
Added Timeouts/taskID change

### LINKED ISSUE #12: Timeouts
Specific timeouts for each state

Add require for block numbers

Need to partition timesteps

### PR DESCRIPTION
**Pull request by hswick**
This PR changes the taskID to a hash of data specific to a task which makes it more specific and solves invalid opcode issue.

taskGiver has to specify time duration for each timeout for the different states when creating a task. the trigger commands will not throw errors when the current blocknumber is greater than equal to what was specified.

Coming up with a method to properly test these triggers is needed next.

Resolves #12

### CODE REVIEW

**Comment by sinahab** [comment]
Solid work! I have two architectural questions here:

---

**1)** My understanding was that all tasks were going to have the same _proportion_ of timeOuts between the different stages. 

E.g. all tasks would have:
1x timeOut between when (task was created) and when (solution needs to be posted).
1x timeOut between when (the solution being posted) and when (verifier needs to commit intent)
1x timeOut between when (the verifier is determined) and when (forced error is revealed)
Etc etc

If this is correct, then the taskGiver only needs to set the _unit_ timeOut is for their task is.
I.e. in `createTask`, they’d set `timeOut` to something like `2` blocks. 
Thereafter, the smart contract would do all calculations itself according to the general formula.

---

**2)** Can we have a more generic `triggerTaskStateChange` function instead of separate trigger functions for each timeout (e.g. `triggerTaskSolveTimeout`, `triggerTaskChallengeQueueTimeout`, etc)?

Given a task’s current state, `triggerTaskStateChange` will already know which state transition can happen. Since it knows the state transition, it also knows what the timeOut for it is meant to be (as timeOut multiplier depends on the type of state transition).

If this is correct, then a generic function should be able to manage all state transitions.

---

What do you think?

**Comment by hswick** [comment]
1) Are you saying in that case there would be a 2 block timeout for each state change listed? I don't think the times between each states should be equal. There would be a lot of wasted time in some states and possibly not enough times in others.
2) I had thought about using a generic stateChange Function. But the issue is most of the states have fairly unique properties to them in terms of what data needs to be output by events and which methods it needs to call. The only two states that are similar are ChallengesAccepted and IntentsRevealed, so the benefit of any clever mechanism as opposed to a more declarative approach is pretty low. Also the way the timeouts are currently setup pose an issue to a generic function. The start of the timer has to be initiated in the **previous** state. Once again, its possible the indices of an array of blocknumbers could be used to represent this and integers passed into a method, but I'm not convinced this is a better implementation than a more declarative approach.

**Comment by sinahab** [comment]
Re:

**1.** What you’re saying re different state changes needing different amounts of time is true. But I think the times are proportionally the same across all tasks.

E.g. like you said, the taskGiver would provide a single integer when they create the task to state how many blocks they imagine solving the task to take. Let’s call this n.

The smart contract would then know to allow:
- (1 * n) blocks between the task being created, and solved.
- 2 blocks (i.e. a fixed number) between the task being solved and challengers posting their intent.
- 2 blocks between the challengers posting their intent, and their solution.
- (1 * n) blocks when a challenger needs to calculate merkle roots and post the result etc etc

I think happens is that the _proportions_ of the timeOuts between states stays the same. The actual multiple (i.e. n) changes given the task difficulty, and needs to be supplied by the taskGiver.

**2.** We know exactly which sequence the states are meant to progress through.

The Task struct needs two keys: `currentState` and `blockStateLastUpdated`.

Then we could have a generic private `stateChangeTimeoutReached’ function which receives taskID as a parameter and returns a boolean. This function looks up the Task’s `currentState`, look up how long the transition to the next state is supposed to take in terms of blocks (this is fully deterministic), and if enough blocks have passed, it returns true. Otherwise, false.

When someone calls a function (e.g. `commitChallenge`, `verifySolution`, etc), the function would have a `require(stateChangeTimeoutReached(taskID)` before proceeding through its logic.

If we do this, we wouldn’t need separate functions for each timeOut. 

Or am I missing something? :D

**Comment by hswick** [comment]
@sinahab I think that might be simpler. I'm still a little uneasy about us getting the formula right, and not giving users more control over their experience. Will post a commit with an implementation of your approach when I get a chance and we can discuss further.

**Comment by hswick** [comment]
That ended up being a much easier change than I thought.

**Comment by sinahab** [comment]
Coolcool! Some comments:

**1)** What do you think re `rebase` onto master, instead of a `merge` (like in this [merge commit](https://github.com/TrueBitFoundation/truebit-contracts/pull/17/commits/1ae0d477e2272c79789af001779c97f741456283))? Two reasons for this:

One – when we merge your branch onto `TruebitFoundation/master`, the commit log will have multiple nested merges inside. This will be hard to reason about in the future.

Two – it seems a bunch of changes from yesterday's PR are being re-created (e.g. all the deposit bonding stuff in TaskBook).

To do this, if you check out the “Replaced timeouts..” commit, you can then do:
```
git checkout master
git pull
git checkout <your-branch>
git rebase master
```

I think we’ll have a clearer commit log and code history using rebase (e.g. [the commit log](https://github.com/TrueBitFoundation/truebit-contracts/commits/master) after yesterday's PR).

**2)** Seems like the last two commits switch back to using `uint` for taskID, whereas the earlier commits had changed it to `byetse32`. Was this planned?

**Comment by hswick** [comment]
1) Normally I do rebase, but for some reason I decided against it. I can redo that.

2) Yeah decided against the hashes. Tests pass fine, and less memory usage.

**Pull request merged**
